"""add category to pitch column

Revision ID: 73f776f87431
Revises: 136b5818cc25
Create Date: 2018-10-13 21:11:44.746588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f776f87431'
down_revision = '136b5818cc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###
